"""Hardware-accelerated time series feature extraction with JAX."""

from tsxtract.extraction import extract_features, to_columns
from tsxtract.feature_settings import (
    DEFAULT_FEATURE_SPECS,
    SPECTRAL_FEATURE_SPECS,
    TEMPORAL_FEATURE_SPECS,
    FeatureSpec,
)
from tsxtract.features import (
    autocorrelation,
    band_energy,
    dominant_frequency,
    kurtosis,
    mad,
    maximum,
    mean,
    median,
    minimum,
    percentile,
    power_bandwidth,
    rms,
    skewness,
    spectral_bandwidth,
    spectral_centroid,
    spectral_entropy,
    spectral_rolloff,
    std,
    variance,
    zero_crossing_rate,
)

__all__ = [
    "extract_features",
    "to_columns",
    "FeatureSpec",
    "DEFAULT_FEATURE_SPECS",
    "TEMPORAL_FEATURE_SPECS",
    "SPECTRAL_FEATURE_SPECS",
    "autocorrelation",
    "band_energy",
    "dominant_frequency",
    "kurtosis",
    "mad",
    "maximum",
    "mean",
    "median",
    "minimum",
    "percentile",
    "power_bandwidth",
    "rms",
    "skewness",
    "spectral_bandwidth",
    "spectral_centroid",
    "spectral_entropy",
    "spectral_rolloff",
    "std",
    "variance",
    "zero_crossing_rate",
]